/* eslint-disable no-multi-spaces */


/* products */
export const RECEIVE_PRODUCTS_SUCCESS  = 'RECEIVE_PRODUCTS_SUCCESS';
export const RECEIVE_PRODUCTS_FAILURE  = 'RECEIVE_PRODUCTS_FAILURE';

export const RECEIVE_PRODUCT_SUCCESS  = 'RECEIVE_PRODUCT_SUCCESS';
export const RECEIVE_PRODUCT_FAILURE  = 'RECEIVE_PRODUCT_FAILURE';

export const RECEIVE_LAST_ADDED_PRODUCTS_SUCCESS  = 'RECEIVE_LAST_ADDED_PRODUCTS_SUCCESS';
export const RECEIVE_LAST_ADDED_PRODUCTS_FAILURE  = 'RECEIVE_LAST_ADDED_PRODUCTS_FAILURE';

export const RECEIVE_RECOMMENDED_PRODUCTS_SUCCESS  = 'RECEIVE_RECOMMENDED_PRODUCTS_SUCCESS';
export const RECEIVE_RECOMMENDED_PRODUCTS_FAILURE  = 'RECEIVE_RECOMMENDED_PRODUCTS_FAILURE';

export const RECEIVE_WOMAN_PRODUCTS_SUCCESS  = 'RECEIVE_WOMAN_PRODUCTS_SUCCESS';
export const RECEIVE_WOMAN_PRODUCTS_FAILURE  = 'RECEIVE_WOMAN_PRODUCTS_FAILURE';

export const CHANGE_PRODUCT            = 'CHANGE_PRODUCT';

/* cart */
export const ADD_PRODUCT_TO_CART       = 'ADD_PRODUCT_TO_CART';
export const CHANGE_PRODUCT_QTY        = 'CHANGE_PRODUCT_QTY';
export const REMOVE_PRODUCT_FROM_CART  = 'REMOVE_PRODUCT_FROM_CART';
export const CLEAR_CART                = 'CLEAR_CART';
export const CART_FAILURE              = 'CART_FAILURE';

/* orders */
export const SEND_ORDER_REQUEST        = 'SEND_ORDER_REQUEST';
export const SEND_ORDER_SUCCESS        = 'SEND_ORDER_SUCCESS';
export const SEND_ORDER_FAILURE        = 'SEND_ORDER_FAILURE';

/* eslint-enable no-multi-spaces */
